<?php
	session_start();
    include('include/connections.php');
	session_unset();
	session_destroy();
	//unset($_SESSION['ADMIN_LOGIN']);
	//unset($_SESSION['ADMIN_USERNAME']);
	header('location:login.php');
	//die();
?>